data "aws_ssm_parameter" "public_subnet_ids" {
    name = "/${var.project_name}/${var.environment}/public_subnet_ids"
}

data "aws_ami" "ami_info" {
    most_recent = true
    owners = ["679593333241"] #Owner ID of AMI OpenVPN Access Server Community Image fe8020*

    filter {
        name = "name"
        values = ["OpenVPN Access Server Community Image-fe8020db-*"] #This OpenVPN generated by AWS, hence we cant use username and pwd, it should require public key to create server and private key to access it or for authorization
    }

    filter {
        name = "virtualization-type"
        values = ["hvm"]
    }

    filter {
        name = "root-device-type"
        values = ["ebs"]
    }
}

data "aws_ssm_parameter" "vpn_sg_id" {
    name = "/${var.project_name}/${var.environment}/vpn_sg_id"
}